import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from matplotlib.animation import FuncAnimation, PillowWriter
from config import ARENA_RADIUS, NEIGHBORS

def generate_gif_from_log(log_path):
    """
    Visualization bridge.
    Reads the trajectory.npz file generated by the Logger and creates a GIF.
    """
    trajectory_file = os.path.join(log_path, "trajectory.npz")
    if not os.path.exists(trajectory_file):
        print(f"[Visu] Error: No trajectory.npz file in {log_path}")
        return

    print(f"[Visu] Loading {trajectory_file}...")
    data = np.load(trajectory_file, allow_pickle=True)
    
    pos = data['pos'] # Shape (T, N, 2)
    phi = data['phi'] # Shape (T, N)
    
    # Parameters retrieved for display
    params = data['params'].item() 
    
    # Plot configuration
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(-ARENA_RADIUS-1, ARENA_RADIUS+1)
    ax.set_ylim(-ARENA_RADIUS-1, ARENA_RADIUS+1)
    ax.add_patch(Circle((0, 0), ARENA_RADIUS, color='r', fill=False, ls='--', alpha=0.5))
    
    title = f"Replay: y_att={params['y_att']:.2f}, Neigh={params.get('NEIGHBORS', NEIGHBORS)}"
    ax.set_title(title)
    ax.set_aspect('equal')
    ax.grid(True, alpha=0.2)

    # Vector initialization (quivers)
    # pos[0] is the initial state
    quiver = ax.quiver(pos[0, :, 0], pos[0, :, 1], 
                       np.cos(phi[0]), np.sin(phi[0]), 
                       color='dodgerblue', scale=25, width=0.005)

    def update(frame):
        # Update positions and directions
        quiver.set_offsets(pos[frame])
        quiver.set_UVC(np.cos(phi[frame]), np.sin(phi[frame]))
        return quiver,

    # Create animation
    ani = FuncAnimation(fig, update, frames=len(pos), interval=30, blit=True)
    
    output_gif = os.path.join(log_path, "animation.gif")
    print(f"[Visu] Generating GIF: {output_gif} (patience...)")
    
    writer = PillowWriter(fps=30)
    ani.save(output_gif, writer=writer)
    plt.close(fig) # Close figure to free memory
    print("[Visu] Done.")

if __name__ == "__main__":
    # Allows manual run on a specific folder
    import sys
    if len(sys.argv) > 1:
        generate_gif_from_log(sys.argv[1])
    else:
        print("Usage: python visualization.py logs/DIR_NAME")